replicaCount: 1

image:
  repository: heojiye/springboot-sample
  tag: "latest"
  pullPolicy: Never  # 로컬 이미지 사용

service:
  type: NodePort
  port: 8080
  nodePort: 30080

ingress:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_PROFILES_ACTIVE
    value: "local" 