apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-sample
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/HeoJiye/gitops-sample
    targetRevision: HEAD
    path: applications/spring-boot-sample
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 